site_name: py-pane Documentation
repo_url: https://github.com/hexane360/pane

docs_dir: 'docs'
site_dir: 'site'
extra_css:
  - style.css

nav:
  - Home: index.md
  - 'Using pane': using.md
  - API:
    - pane.convert: api/convert.md
    - pane.annotations: api/annotations.md
    - pane.types: api/types.md
    - pane.errors: api/errors.md
    - pane.converters: api/converters.md
    - pane.field: api/field.md
    - pane.classes: api/classes.md
    - pane.util: api/util.md

theme:
  name: material
  palette:
    primary: purple
    accent: green
  featutures:
    - navigation.tabs
   #- navigation.tabs.sticky
    - navigation.expand
   #- navigation.indexes  seems broken
extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - autorefs
  - mkdocstrings:
      custom_templates: templates
      handlers:
        python:
          paths: [.]
          import:
            # 3rd-party object inventories
            - https://docs.python.org/3/objects.inv
          options:
            show_if_no_docstring: true
            show_root_heading: true
            members_order: source
            filters: ["!^_", "!^__(all|repr|str)__$", "!^(FromData)?[TUKV](_co(ntra)?)?$", '_converter']
  - mike:
      version_selector: true

watch:
  - pane/
